# Domain Event Publisher 설정 예시
ball:
  events:
    domain:
      enabled: true
      async: true
      enable-retry: true
      max-retry-attempts: 3
      retry-delay-ms: 1000
      timeout-ms: 5000
      enable-debug-logging: false
      enable-metrics: true
      validation:
        strict: true
        required-fields:
          - "id"
          - "type" 
          - "occurredAt"
        max-id-length: 255
        max-type-length: 100

# 개발 환경 전용 설정
---
spring:
  config:
    activate:
      on-profile: dev

ball:
  events:
    domain:
      enable-debug-logging: true
      async: false  # 디버깅을 위해 동기 처리

# 운영 환경 전용 설정  
---
spring:
  config:
    activate:
      on-profile: prod

ball:
  events:
    domain:
      enable-debug-logging: false
      async: true
      enable-metrics: true
      timeout-ms: 3000  # 더 짧은 타임아웃

# 테스트 환경 전용 설정
---
spring:
  config:
    activate:
      on-profile: test

ball:
  events:
    domain:
      async: false  # 테스트에서는 동기 처리
      enable-retry: false  # 테스트에서는 재시도 비활성화
      validation:
        strict: false  # 테스트용 이벤트는 덜 엄격하게
